version: '3.8'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local


 